# Base Image
FROM python:3.13.2

# Copy the python file into the image/container
COPY script.py /app/script.py

# Set working directory
WORKDIR /app

# Run the python script
CMD ["python", "script.py"]